name: Automatic pull request review

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  review_pull_request:
    name: Pull request review
    runs-on: macOS-12
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.5.0
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/cache@v3
      id: bunlderCache
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
# restore
    - uses: actions/cache/restore@v3
      id: cache
      with:
        path: SourcePackages/
        key: spm-cache-{{ checksum "CryptoPrices.xcodeproj/project.xcworkspace/ xcshareddata/swiftpm/Package.resolved" }}

    - name: Setup
      run: make setup

    - name: Lint
      run: make lint

    - name: Build and Test
      run: bundle exec fastlane buildAndTest --verbose
      env:
        CI: true
# save
    - uses: actions/cache/save@v3
      with:
        path: SourcePackages/
        key: spm-cache-{{ checksum "CryptoPrices.xcodeproj/project.xcworkspace/ xcshareddata/swiftpm/Package.resolved" }}

    - name: Clean up previous code coverage report
      run: bundle exec fastlane cleanUpOutput
