name: Deploy Release Build To Firebase

on:
  push:
    branches: [ release/** ]
  workflow_dispatch:

jobs:
  Lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Run SwiftLint
      uses: norio-nomura/action-swiftlint@3.1.0
      with:
        args: --strict
        
  build:
    name: Build
    runs-on: macOS-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.5.0
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            
    - name: Bundle install
      run: bundle install

    # TODO: Enable this step when the CI pipeline is ready
    # - name: Build and Test
    #   run: bundle exec fastlane build_and_test

    - name: Match Ad-hoc
      run: bundle exec fastlane syncAdHocProductionCodeSigning
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASS }}

    - name: Build Production App and Distribute to Firebase
      run: bundle exec fastlane buildProductionAndUploadToFirebase
      env:
        FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
